ioParams:
  inputPath: ./inputs/test2.mp4
  outputPath: final_guitar2.mov
  intermediateResults: False

featureParams:
  maxCorners: 100
  qualityLevel: 0.01
  minDistance: 10

trackingParams:
  winSize: !!python/tuple [15, 15]
  maxLevel: !!python/int 2
  criteria: !!python/tuple [2, 10, 0.03]

meshSize: [64, 32]